# Generated by Django 3.0.3 on 2020-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Magamról')),
                ('profile_pic', models.ImageField(upload_to='media/about', verbose_name='Profilkép')),
            ],
        ),
        migrations.AlterModelOptions(
            name='homemessage',
            options={'verbose_name_plural': 'Home oldal'},
        ),
        migrations.AlterField(
            model_name='homemessage',
            name='message',
            field=models.TextField(verbose_name='Üzenet'),
        ),
        migrations.AlterField(
            model_name='homemessage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Cím'),
        ),
    ]
