# Generated by Django 3.0.3 on 2020-04-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200405_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='profile_pic',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='photo',
            new_name='image',
        ),
    ]
